### ISSUE TITLE
The dropdown selection in the WebView is not working

### ISSUE THREAD

**Issue by Yosuke-li** [jnschulze/flutter-webview-windows#138] opened 2022-05-19 01:53 UTC
https://user-images.githubusercontent.com/36600238/169186673-9f516649-979d-4c36-a18e-a510079a094c.mov

look this video.how to fix it? Thanks

**Comment by angle222** [comment] 2022-05-23 07:32
the same problems as me @jnschulze

**Comment by Spitzbua** [comment] 2022-06-08 09:09
I have a slightly different behaviour. The menu list does not open when clicking on the arrow and no selection can be made. I thought the issue is fixed with new Webview2 sdk version https://github.com/MicrosoftEdge/WebView2Feedback/issues/1693

**Comment by hydev777** [comment] 2022-08-15 13:38
I have the same issue that @Spitzbua has, whenever I clicked a dropdown it does not open.

**Comment by Dobariyakishan** [comment] 2022-12-29 12:15
any update on this issue??

**Comment by rubencscas** [comment] 2023-01-11 11:51
I also have the same problem. Anyone has solved this problem?

**Comment by njuptzwt** [comment] 2023-06-19 01:17
I also have the same problem. Any solution?

**Comment by masmilondev** [comment] 2023-08-04 16:37
I also have the same problem. Any solution?

**Comment by yagnesh1406** [comment] 2024-05-20 11:59
I am facing the same issue.

**Comment by LukasSkywalker** [comment] 2024-05-21 06:09
I switched to https://github.com/jakky1/webview_win_floating because of this issue. With WebviewWinFloating, everything works.

**Closed** 2024-10-08 13:40 UTC
